### ISSUE TITLE
Question: Scala 3 support?

### ISSUE THREAD

**Issue by coffius** [endless4s/endless#175]
I wonder if you have any plans of adding support of  Scala 3 to `endless4s`?

**Comment by jchapuis** [comment]
Great question, we're just stuck for the moment because `cats-tagless` is still not ported to Scala 3. It might happen in the near future https://github.com/typelevel/cats-tagless/issues/170#issuecomment-1225129810 in which case we could provide a Scala 3 build, yes. Also, the Akka runtime would then rely on the experimental support for Scala 3 (we do not have experience with that).

**Comment by cloudcompute** [comment]
@jchapuis 

Looks like is `cats-tagless` supports `Scala 3`

https://github.com/typelevel/cats-tagless/tree/master/core/src/main/scala-3/
